version: 2.1
setup: true

orbs:
  path-filtering: circleci/path-filtering@3.0.0

workflows:
  determine-changes:
    jobs:
      - path-filtering/filter:
          base-revision: main
          config-path: .circleci/continue_config.yml
          mapping: |
            src/.* run-build true
            Dockerfile run-build true
            scripts/.* run-build true
            \.circleci/.* run-build true
            aws/.* run-build true
